version: '3.3'
services:
  frpc:
    container_name: frpc
    restart: always
    network_mode: host
    volumes:
      - '/path/to/frpc.toml:/etc/frp/frpc.toml'
    image: anyshpm/frpc:latest
    command: frp -c /etc/frp/frpc.toml

networks:
  default:
    external:
      name: "host"
